//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod lamport_id;
pub mod points;
pub mod power;
pub mod proposal;
pub mod proposal_option;
pub mod users;
pub mod vote;
pub mod vote_option;
