//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::groups::Entity as Groups;
pub use super::lamport_id::Entity as LamportId;
pub use super::points::Entity as Points;
pub use super::power::Entity as Power;
pub use super::proposals::Entity as Proposals;
pub use super::users::Entity as Users;
pub use super::vote::Entity as Vote;
