//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "proposals")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub proposal_id: String,
    pub group_id: String,
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub options: Vec<String>,
    pub created_by: String,
    pub start_time: DateTimeWithTimeZone,
    pub end_time: DateTimeWithTimeZone,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
